name: Kapper Appointment Checker

on:
  schedule:
    - cron: '10,40 5-20 * * *'  # UTC time
  workflow_dispatch:

jobs:
  check-appointments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests resend
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Run appointment checker
        env:
          AUTH_URL: ${{ secrets.AUTH_URL }}
          API_URL: ${{ secrets.API_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          USER_ID: ${{ secrets.USER_ID }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_FROM_EMAIL: ${{ secrets.MAILGUN_FROM_EMAIL }}
          MAILGUN_TO_EMAIL: ${{ secrets.MAILGUN_TO_EMAIL }}
          MAILGUN_API_URL: ${{ secrets.MAILGUN_API_URL }}
          MAIL_TEMPLATE_LINK: ${{ secrets.MAIL_TEMPLATE_LINK }}
          ORIGIN: ${{ secrets.ORIGIN }}
          REFERER: ${{ secrets.REFERER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python "KapperAlert -Github Version.py"
        
      - name: Commit and push if state changed
        run: |
          git add previous_notified.pkl || true
          git commit -m "Update appointment state [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
