name: Kapper Appointment Checker

on:
  schedule:
    - cron: '*/15 * * * *' # Run every 15 minutes
  workflow_dispatch: # Allow manual runs

jobs:
  check-appointments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Download previous state
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: previous-notified
          path: .
        continue-on-error: true  # Don't fail if artifact doesn't exist
        
      - name: Run appointment checker
        env:
          AUTH_URL: ${{ secrets.AUTH_URL }}
          API_URL: ${{ secrets.API_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          USER_ID: ${{ secrets.USER_ID }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_FROM_EMAIL: ${{ secrets.MAILGUN_FROM_EMAIL }}
          MAILGUN_TO_EMAIL: ${{ secrets.MAILGUN_TO_EMAIL }}
          MAILGUN_API_URL: ${{ secrets.MAILGUN_API_URL }}
          MAIL_TEMPLATE_LINK: ${{ secrets.MAIL_TEMPLATE_LINK }}
          ORIGIN: ${{ secrets.ORIGIN }}
          REFERER: ${{ secrets.REFERER }}
        run: python "KapperAlert -Github Version.py"
        
      - name: Check if state file exists
        id: check-file
        run: |
          if [ -f previous_notified.pkl ]; then
            echo "file-exists=true" >> $GITHUB_OUTPUT
            echo "State file exists"
          else
            echo "file-exists=false" >> $GITHUB_OUTPUT
            echo "State file does not exist"
          fi
          
      - name: Save state for next run
        if: steps.check-file.outputs.file-exists == 'true'
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: previous-notified
          path: previous_notified.pkl
          retention-days: 1
